### PR TITLE
Example HMC inference for NPZD box model with Turing.jl

### LINKED ISSUE #11: Try to do inference with NPZD box model
- EnsembleKalmanProcesses
- Turing.jl (but might not work because Oceananigans)

### PR DESCRIPTION
**Pull request by radka-j**
Closes #11

### CODE REVIEW

File: examples/inference_hmc.jl [hunk 1]
```diff
@@ -0,0 +1,128 @@
...
+
+@model function fit_NPZD(data, prob)
+    # prior distributions centered at true value and with upper limit at ~ +2sigma
+    μ₀ ~ truncated(Normal(0.6989 / day, 0.1 / day); lower=0, upper=0.9 / day)
+    kₙ ~ truncated(Normal(2.3868, 0.5); lower=0, upper=3.5)
+    lᵖᵈ ~ truncated(Normal(0.0101 / day, 0.01 / day); lower=0, upper=0.03 / day)
+    α ~ truncated(Normal(0.1953 / day, 0.05 / day); lower=0, upper=0.3 / day)
+
+    # observation noise
+    σ ~ InverseGamma(2, 3)
```
Comment (ljwolf) [inline examples/inference_hmc.jl:86]: I'd try for a Truncated `Cauchy(0,nu)` prior here for stability, following the [Poulson & Scott (2011)](https://www.semanticscholar.org/reader/6a1701a9a95a1f42d04c60d80966e9f5a611cfb9) arguments about its behavior in the limit and its implicit shrinkage properties.
